main: xyz.minecat.Minecat
name: minecat
version: 2.1.1
author: ooliver1 - Oliver WIlkes
database: false
api: "go away vscode this isn't required"
api-version: 1.13
commands:
  link:
    description: Get your auth code for minecat!
    usage: /<command>
