on: [push, pull_request]

name: Build

jobs:
  build:
    strategy:
      matrix:
        java: [8, 17]

    runs-on: ubuntu-latest

    name: Java ${{ matrix.java }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Execute Gradle build
        run: ./gradlew build --no-daemon
