on: [push, pull_request]

name: Build

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 16, 17]
        distribution: [temurin, zulu, liberica, microsoft, corretto]

    runs-on: ${{ matrix.os }}

    name: Java${{ matrix.java }}-${{ matrix.distribution }} Gradle${{ matrix.gradle }} ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Execute Gradle build
        run: ./gradlew build
