on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
        gradle: [2, 3, 4, 5, 6, 7]
        distribution: [temurin, zulu, liberica, microsoft, corretto]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle }}
      - name: Execute Gradle build
        run: ./gradlew build
