on: [push, pull_request]

name: Build

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 16, 17]
        gradle: [2, 3, 4, 5, 6, 7]
        distribution: [temurin, zulu, liberica]

    runs-on: ${{ matrix.os }}

    name: Java${{ matrix.java }}-${{ matrix.distribution }} Gradle${{ matrix.gradle }} ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle }}
      - name: Execute Gradle build
        run: ./gradlew build
