on:
  push:
    branches:
      # add back master when merged
      #     - master
      - dev

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create release if needed
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          extra-files: plugin/build.gradle.kts
          default-branch: ${{ github.ref_name }}
      - name: Parse semver string
        if: steps.release.outputs.release_created
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.release.outputs.tag_name }}
      - name: Mark as pre-release
        if: ${{ (steps.semver_parser.outputs.prerelease != '') || (steps.semver_parser.outputs.major == '0') }}
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        with:
          prerelease: true
